### ISSUE TITLE
bug - BigQuery cluster columns reference hard coded customer column name

### ISSUE THREAD

**Issue by awoehrl** [bcodell/dbt-activity-schema#29]
When using the `dbt_aql.cluster_keys().cluster_by` macro, the cluster keys are defined via a `columns` variable, which contains hard coded values for each column. For some macros there is a mechanism that overwrites the hard coded values with the actual name defined in the config. However, for `dbt_aql.cluster_keys().cluster_by` this mechanism seems to be missing or not working, which results in rendering the hard coded column names in the final DDL statement.

In the generated code below you can see that "customer" is inserted, which is the hard coded value, where there should be the value defined in `dbt_project.yml` instead:

```
    create or replace table `dwh`.`dev`.`customer_stream`
      
    partition by timestamp_trunc(ts, month)
    cluster by activity, activity_occurrence, customer
```

**Comment by zkeller89** [comment]
Pretty sure I just ran into this as well. I'm a bit new to the code - so grant me some slack, but I think the problematic code might be at the bottom of this chunk in the `schema_columns()` macro:
https://github.com/bcodell/dbt-aql/blob/131ddcb881cf03a0c7b115f40925da0cc09e12ee/macros/activity_schema/constants/columns.sql#L41-L60

As it references the project-level column configs instead of the stream-level column configs.

**Comment by bcodell** [comment]
Hey @awoehrl and @zkeller89! I should have a patch in place for this later today. In the immediate term it will only support clustering the full stream (since that's currently the only activity schema implementation that this project supports), but I'll add clustering support for the one table per activity implementation once I ship that functionality for the project (currently in progress).

**Comment by zkeller89** [comment]
Workaround ain't too bad so no rush - just figured i'd drop in what my limited pokin' around yielded

**Comment by bcodell** [comment]
Hey @zkeller89 @awoehrl this should now be resolved. Packaged up in release version 0.1.9 - let me know if you bump into anything else. Thanks both!
