### ISSUE TITLE
documentation doesn't articulate core use case / target audience

### ISSUE THREAD

**Issue by mike-weinberg** [bcodell/dbt-activity-schema#61]
Hi Bryce =)

Reading the docs here, it seems like implicitly there's an emphasis on web event use cases, funnel analysis, etc, but I don't see that anywhere explicitly. 

I've got a use case that's pretty different and I can't quite tell if this package is right for us. we often get activity data in terms of _intervals_  and many intervals may be missing. this is to say that we have prior expectations about what data we should get and when, and our work tends to have to do with the alignment of the interval data we get with a set of scheduled events which are "fulfilled" by the activity. Missing activity records therefore need to be counted and possibly infilled in specific ways, and they may arrive late and need to be backfilled _regularly_. In general we are trying to simply measure the overlap between these event windows and the activity of the entities whose activities can be linked to that event (each event will pertain to a set of IOT-style actor entities whose activities can contribute to at most one event at a time) 

For us, we use window functions a lot for this, and are just beginning to play with match_recognize in snowflake. I *think* that approach will work for us as a generalizable pattern, but I wonder if our approach is missing things covered by the canonical activity framework.

**Comment by bcodell** [comment]
Hey @mike-weinberg - thanks for opening this issue! You highlighted a few different topics so going to try to address each:
> Reading the docs here, it seems like implicitly there's an emphasis on web event use cases, funnel analysis, etc, but I don't see that anywhere explicitly.

Given the event-like structure of the activity stream and the sequential nature in which activities relate to each other when building datasets, I think I can see where this perception originates. Ultimately, though, the methodology is not unique to web events and funnel analysis. I regularly build current-state datasets from the streams I've implemented. I personally view activity schema as an intermediate transformation standard that coerces downstream consumers to access the data in a consistent fashion. So ad hoc datasets or stable dimensional models can be built on top of it. There are tradeoffs to this approach, of course, and while I have some blogging I intend to do on that subject, I do think the documentation should largely be dedicated to the implementation of the project (which is also why I articulate in the readme that some prior knowledge of activity schema modeling is required). Perhaps I can link to the framework spec there, though, for easy access for folks who don't yet have that context.

> we often get activity data in terms of intervals and many intervals may be missing...

If I'm understanding correctly, this is effectively telemetry data you're modeling, yes? In the case of telemetry data, the activities I've produced are activities that represent when an attribute being tracked in the telemetry changes. So, for example, if the telemetry data is tracking temperature and sends an event every 5 minutes, then the activity I'd recommend is "temperature_changed" and only include an activity occurrence each time the temperature has changed relative to the previous logged occurrence. But there are other dynamics at play (e.g. late-arriving events) that could affect the recommendation, and also I didn't totally follow the use case due to lack of domain context - can you provide an example with more specifics? What's an example event? What questions are you trying to answer on behalf of the business? That would help me refine a recommendation here. Happy to chat live if easier.

> For us, we use window functions a lot for this, and are just beginning to play with match_recognize in snowflake.

No sales agenda here, and if your team is exclusively trying to address a specific use case isolated to the event data you described, then using something like `match_recognize` seems like the best path forward. Will fit in nicely with your existing stack (just write a query using `match_recognize` in a sql file in your dbt project), and doesn't come with the overhead of having to integrate a new dbt package that's highly opinionated about code structure (i.e. comes with a meaningful migration effort). Where activity schema shines brightest is when trying to reconcile different types of data in different formats in different systems. So, if your team is trying to connect user attributes from a CRM to this telemetry data, activity schema (and possibly this package) could be a good fit.

Lmk what you think!

**Comment by bcodell** [comment]
Hey @mike-weinberg doing some issue cleanup - this appears to have gotten stale so closing for now. Feel free to reopen if you'd like to continue the discussion!
