### ISSUE TITLE
build_json function not working for redshift

### ISSUE THREAD

**Issue by matthieu-carmeille** [bcodell/dbt-activity-schema#74]
The function generates an invalid json 

Code:

{{ config(
    materialized='table',
    sort=dbt_activity_schema.cluster_keys().sort,
    dist=dbt_activity_schema.cluster_keys().dist,
    stream='invoice_charges_activity',
    data_types={
                'is_reccuring': type_int(),
                'charge_name': type_string(),
                }
        ) 
}}

with charges as (
    SELECT
        organisation_id as {{ dbt_activity_schema.customer_column('invoice_charges_activity') }},
        period as {{ dbt_activity_schema.schema_columns().ts }},
        1 as activity_id,
        organisation_id as anonymous_user_id,
        tariff_plan_charges as revenue_impact,
        charge_name,
        is_reccuring
    FROM core.fct_invoice
    CROSS JOIN staging.charge_mapping as cm 
    WHERE  cm.charge_name = 'tariff_plan_charges'
    AND tariff_plan_charges > 0
    
)

{{ dbt_activity_schema.build_activity(
    cte='charges',
    null_columns=['link']
) }}

![image](https://github.com/user-attachments/assets/9e027ef5-5e98-41fa-bf70-bb6869d99345)

**Comment by bcodell** [comment]
Hey @matthieu-carmeille - nice catch and thanks for flagging! Do you want to take a stab at this? In case you do, relevant code snippet to modify is linked below, and contribution workflow is fork the repo, commit changes there, and open a PR. Otherwise I can update later today or tomorrow. Let me know!

https://github.com/bcodell/dbt-activity-schema/blob/main/macros/activity_schema/activity/build_json.sql#L34-L45

**Comment by matthieu-carmeille** [comment]
Forked and modified the redshift function but output unchanged. So seems like the redshift function is not even picked.

Had a redshift function like this in mind: 

{%- macro redshift__build_json(data_types) -%}
    {%- if data_types is not none -%}
    {%- set features = data_types.keys() -%}
    '{' || 
        {%- for feature in features -%}
        {%- if not loop.first -%}', '{% endif -%}
        '"'||{{ feature }}||'": "' || cast({{ feature }} as {{ dbt.type_string() }}) || '"'{%- if not loop.last -%}||{% endif %} 
        {%- endfor -%}
    || '}'
    {%- else -%}
    cast(null as varchar)
    {%- endif -%}
{%- endmacro -%}

We can take a look together to fix it if you want.

**Comment by bcodell** [comment]
@matthieu-carmeille hmm that code looks right, and I see the update in your fork.

As a starting point, I think we can rule out the theory that the package isn't picking up the redshift-specific code. Based on the image you shared where the code is running successfully against your redshift cluster and just creating a string that's not a valid JSON string, the code is definitely picking up a version of the redshift-specific implementation; otherwise it would use syntax that's not compatible with redshift and the model wouldn't materialize. (Side note - great to see you re-aliasing the JSON column as `attributes` instead of `feature_json`!)

I imagine you did this while troubleshooting, but asking to make sure we've checked all our bases: did you update your `packages.yml` file to use the forked version, and run a full `dbt clean && dbt deps` after making that update? Packages file should look something like this:

```
packages:
  - git: "https://github.com/emnify/dbt-activity-schema"
    revision: main
```

If you made those changes and are still running into issues, then my next suggestion would be to update the `packages.yml` syntax to install from your computer's local version of the package using the [local package syntax](https://docs.getdbt.com/docs/build/packages#local-packages), then running clean and deps again. If that still doesn' work, then try removing `package-lock.yml` entirely from your dbt project directory and then run clean and deps from that point. If, after that point, it's still not working, let me know and we can find some time for a call to troubleshoot live.

**Comment by matthieu-carmeille** [comment]
Thanks Bryce. Yes i updated the package file and and did the dbt clean. Will try from the local version then.

**Comment by bcodell** [comment]
Sounds good! Keep me posted. Also, would you mind posting compiled sql here for reference?

**Comment by matthieu-carmeille** [comment]
created PR [here](https://github.com/bcodell/dbt-activity-schema/pull/75)
